name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare deployment directory
        run: |
          mkdir dist
          cp index.html dist/
          cp styles.css dist/
          cp .nojekyll dist/

      - name: Replace {{COMMIT_HASH}} in index.html
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/{{COMMIT_HASH}}/$COMMIT_HASH/g" dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist