name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get short commit hash and inject into index.html
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/{{COMMIT_HASH}}/$COMMIT_HASH/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # or your build output directory